---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: git-upload7
  namespace: git-upload7
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "5"
    limits.memory: "5Gi"
    pods: "20"
