apiVersion: v1
kind: Namespace
metadata:
  name: git-upload2
  labels:
    environment: testing
    created-by: buildpiper-custom-upload
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: git-upload2
  namespace: git-upload2
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "5"
    limits.memory: "5Gi"
    pods: "20"
