apiVersion: v1
kind: Namespace
metadata:
  name: test-custom-namespace
  labels:
    environment: testing
    created-by: buildpiper-custom-upload
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-custom-resourcequota
  namespace: test-custom-namespace
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "5"
    limits.memory: 5Gi
