apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  APP_ENV: {{ .Values.data.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.data.LOG_LEVEL | quote }}
  APP_NAME: {{ .Values.data.APP_NAME | quote }}
